import type { Banner, Category, Product } from '../types';

export const STATIC_BANNERS: Banner[] = [
  {
    id: 1,
    title: 'Authentic Mughlai Cuisine',
    subtitle: 'Rich curries, kebabs & biryanis straight from the tandoor',
    image_url: 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=1200',
    link_url: '/menu',
    cta_text: 'Order Now',
    sort_order: 1,
    is_active: 1,
  },
  {
    id: 2,
    title: 'Hyderabadi Dum Biryani',
    subtitle: 'Slow-cooked aromatic basmati with tender meat & saffron',
    image_url: 'https://images.pexels.com/photos/12737656/pexels-photo-12737656.jpeg?auto=compress&cs=tinysrgb&w=1200',
    link_url: '/menu?category=3',
    cta_text: 'Try Biryani',
    sort_order: 2,
    is_active: 1,
  },
  {
    id: 3,
    title: 'Wood-Fired Tandoori Nights',
    subtitle: 'Freshly grilled kebabs & naans baked in our clay oven',
    image_url: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1200',
    link_url: '/menu',
    cta_text: 'Explore Starters',
    sort_order: 3,
    is_active: 1,
  },
];

export const STATIC_CATEGORIES: Category[] = [
  { id: 1, name: 'Starters', slug: 'starters', description: 'Crispy & grilled starters', image_url: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&w=400', sort_order: 1, is_active: 1, product_count: 8 },
  { id: 2, name: 'Biryani', slug: 'biryani', description: 'Aromatic dum biryani', image_url: 'https://images.pexels.com/photos/12737656/pexels-photo-12737656.jpeg?auto=compress&w=400', sort_order: 2, is_active: 1, product_count: 6 },
  { id: 3, name: 'Curries', slug: 'curries', description: 'Rich & creamy curries', image_url: 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&w=400', sort_order: 3, is_active: 1, product_count: 10 },
  { id: 4, name: 'Breads', slug: 'breads', description: 'Tandoori breads', image_url: 'https://images.pexels.com/photos/1603901/pexels-photo-1603901.jpeg?auto=compress&w=400', sort_order: 4, is_active: 1, product_count: 5 },
  { id: 5, name: 'Kebabs', slug: 'kebabs', description: 'Grilled seekh & galouti', image_url: 'https://images.pexels.com/photos/410648/pexels-photo-410648.jpeg?auto=compress&w=400', sort_order: 5, is_active: 1, product_count: 7 },
  { id: 6, name: 'Desserts', slug: 'desserts', description: 'Sweet endings', image_url: 'https://images.pexels.com/photos/45202/brownie-dessert-cake-sweet-45202.jpeg?auto=compress&w=400', sort_order: 6, is_active: 1, product_count: 4 },
  { id: 7, name: 'Beverages', slug: 'beverages', description: 'Refreshing drinks & lassi', image_url: 'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg?auto=compress&w=400', sort_order: 7, is_active: 1, product_count: 6 },
];

export const STATIC_PRODUCTS: Product[] = [
  {
    id: 1, category_id: 1, name: 'Seekh Kebab', slug: 'seekh-kebab',
    description: 'Minced mutton with spices, charcoal grilled to perfection',
    price: 280, discount_price: 240,
    image_url: 'https://images.pexels.com/photos/410648/pexels-photo-410648.jpeg?auto=compress&w=600',
    is_veg: 0, is_featured: 1, is_best_seller: 1, preparation_time: 20,
    rating: 4.8, sort_order: 1, stock_status: 'in_stock', is_active: 1,
    category_name: 'Starters', avg_rating: 4.8, review_count: 124,
  },
  {
    id: 2, category_id: 2, name: 'Chicken Dum Biryani', slug: 'chicken-dum-biryani',
    description: 'Hyderabadi-style slow-cooked biryani with tender chicken & aromatic spices',
    price: 320, discount_price: 280,
    image_url: 'https://images.pexels.com/photos/12737656/pexels-photo-12737656.jpeg?auto=compress&w=600',
    is_veg: 0, is_featured: 1, is_best_seller: 1, preparation_time: 30,
    rating: 4.9, sort_order: 1, stock_status: 'in_stock', is_active: 1,
    category_name: 'Biryani', avg_rating: 4.9, review_count: 287,
  },
  {
    id: 3, category_id: 3, name: 'Butter Chicken', slug: 'butter-chicken',
    description: 'Tender chicken in a rich, creamy tomato-cashew gravy with aromatic spices',
    price: 340, discount_price: 299,
    image_url: 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&w=600',
    is_veg: 0, is_featured: 1, is_best_seller: 1, preparation_time: 25,
    rating: 4.7, sort_order: 1, stock_status: 'in_stock', is_active: 1,
    category_name: 'Curries', avg_rating: 4.7, review_count: 198,
  },
  {
    id: 4, category_id: 2, name: 'Veg Biryani', slug: 'veg-biryani',
    description: 'Fragrant basmati rice with seasonal vegetables & whole spices',
    price: 220, discount_price: 189,
    image_url: 'https://images.pexels.com/photos/1346066/pexels-photo-1346066.jpeg?auto=compress&w=600',
    is_veg: 1, is_featured: 1, is_best_seller: 0, preparation_time: 25,
    rating: 4.5, sort_order: 2, stock_status: 'in_stock', is_active: 1,
    category_name: 'Biryani', avg_rating: 4.5, review_count: 89,
  },
  {
    id: 5, category_id: 3, name: 'Paneer Tikka Masala', slug: 'paneer-tikka-masala',
    description: 'Grilled cottage cheese cubes in a spicy, tangy tomato-onion masala',
    price: 300, discount_price: 260,
    image_url: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&w=600',
    is_veg: 1, is_featured: 1, is_best_seller: 1, preparation_time: 20,
    rating: 4.6, sort_order: 2, stock_status: 'in_stock', is_active: 1,
    category_name: 'Curries', avg_rating: 4.6, review_count: 156,
  },
  {
    id: 6, category_id: 1, name: 'Hara Bhara Kebab', slug: 'hara-bhara-kebab',
    description: 'Pan-fried spinach & pea patties with mint chutney — crispy outside, soft inside',
    price: 180, discount_price: 149,
    image_url: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&w=600',
    is_veg: 1, is_featured: 0, is_best_seller: 1, preparation_time: 15,
    rating: 4.4, sort_order: 3, stock_status: 'in_stock', is_active: 1,
    category_name: 'Starters', avg_rating: 4.4, review_count: 62,
  },
  {
    id: 7, category_id: 5, name: 'Galouti Kebab', slug: 'galouti-kebab',
    description: 'Melt-in-the-mouth minced mutton kebabs, a royal Lucknawi delicacy',
    price: 360, discount_price: 320,
    image_url: 'https://images.pexels.com/photos/410648/pexels-photo-410648.jpeg?auto=compress&w=600',
    is_veg: 0, is_featured: 1, is_best_seller: 1, preparation_time: 25,
    rating: 4.9, sort_order: 1, stock_status: 'in_stock', is_active: 1,
    category_name: 'Kebabs', avg_rating: 4.9, review_count: 201,
  },
  {
    id: 8, category_id: 6, name: 'Gulab Jamun', slug: 'gulab-jamun',
    description: 'Soft milk-solid dumplings soaked in rose-saffron sugar syrup',
    price: 120, discount_price: null,
    image_url: 'https://images.pexels.com/photos/45202/brownie-dessert-cake-sweet-45202.jpeg?auto=compress&w=600',
    is_veg: 1, is_featured: 0, is_best_seller: 1, preparation_time: 10,
    rating: 4.7, sort_order: 1, stock_status: 'in_stock', is_active: 1,
    category_name: 'Desserts', avg_rating: 4.7, review_count: 113,
  },
];
